services:
  api:
    build: .
    restart: unless-stopped
    ports: 
      - ${PORT}:${PORT}
    # Comment out the volumes section to boot the application how it would be in production
    volumes:
      - .:/app
      - ./config:${COREDNS_CONFIG_ROOT}
    expose:
      - ${PORT}
    # Comment out entrypoint section to boot the application how it would be in production
    entrypoint: ['npm','--prefix', '/app', 'run', 'start:debug' ]